name: pull_requests

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v1
      - name: Dependencies
        run: npm ci
        shell: bash
      - name: Build
        run: npm run build
        shell: bash
      - name: Test
        run: npm test
        shell: bash
