name: Release

on:
  push:
    tags:
    - '*'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Draft Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false
  mac:
    runs-on: macOS-latest
    needs: draft-release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v1
    - name: Update Version
      env:
        version: ${{ github.ref }}
      run: npm version ${version:10} --allow-same-version
    - name: Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Package
      run: npm run dist
    - name: Debug
      run: ls dist

