name: Release

on:
  push:
    branches:
      master
    tags:
    - '*'

jobs:
  mac:
    runs-on: macOS-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: node
      uses: actions/setup-node@v1
    - name: dependencies
      run: npm ci
    - name: build
      run: npm run build
    - name: package
      run: npm run dist
    - name: debug
      run: ls dist

