name: Release

on:
  push:
    tags:
      - '*'

jobs:
  mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v1
      - name: Set Version
        env:
          ref: ${{ github.ref }}
        run: npm version ${ref:10} --allow-same-version
      - name: Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Package
        run: npm run dist
      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        with:
          name: mac
          path: dist
