name: Release

on:
  push:
    branches:
      master
    tags:
    - *

jobs:
  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build
    - run: npm run dist
    - run: ls dist

