name: Release

on:
  push:
    tags:
      - '*'

jobs:
  mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v1
      - name: Version
        env:
          ref: ${{ github.ref }}
        run: echo "::set-env name=version::${ref:10}"
        shell: bash
      - name: Set Npm Version
        run: npm version ${{ env.version }} --allow-same-version
        shell: bash
      - name: Dependencies
        run: npm ci
        shell: bash
      - name: Build
        run: npm run build
        shell: bash
      - name: Package
        run: npm run dist
        shell: bash
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: dist
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v1
      - name: Version
        env:
          ref: ${{ github.ref }}
        run: echo "::set-env name=version::${ref:10}"
        shell: bash
      - name: Set Npm Version
        run: npm version ${{ env.version }} --allow-same-version
        shell: bash
      - name: Dependencies
        run: npm ci
        shell: bash
      - name: Build
        run: npm run build
        shell: bash
      - name: Package
        run: npm run dist
        shell: bash
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: dist
